runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /img
  static_dir: assets/img

- url: /robots.txt
  static_files: assets/txt/robots.txt
  upload: assets/txt/robots.txt

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
